server.port=8080
spring.application.name=superex

spring.datasource.url=jdbc:mysql://localhost:3306/superex
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
